spring:
  server:
    port : 8081
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/amigoscode
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
server:
  error:
    include-binding-errors: always
    include-message: always
