server:
  port : 8081

spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/amigoscode
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
        show_sql: 'true'